#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/ashiklomanov/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# wmnd &
# wmsmixer -w &
xrdb ~/.Xresources                     # Update Xresources
lxpolkit &                             # Lightweight (LX) authentication daemon
nm-applet &                            # Network manager
~/dotfiles/misc/touchpad-settings.sh   # Disable tap to click and other settings
nitrogen --restore                     # Set background image

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/ashiklomanov/.fluxbox/log"
