#! /bin/sh

# Reload this file with Mod + Shift + R

# Keyboard event monitor
pgrep sxhkd || sxhkd &

# Fix fullscreen with xfce4-panel
#xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n xfce4-panel)

# Set up monitors
bspc monitor "DP-1" -d $(printf 'desktop-%01d ' {1..6})
bspc monitor "HDMI-1" -d $(printf 'hdmi-%01d ' {1..6})
bspc monitor "eDP-1" -d $(printf 'laptop-%01d ' {1..6})

bspc config focused_border_color '#F3FF6F'
bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

# Application rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Orage state=floating
bspc rule -a Gpick state=floating
bspc rule -a R_x11 state=floating
bspc rule -a Thunar state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Pavucontrol state=floating

# Tabs Outliner
bspc rule -a Chromium:crx_eggkanocgddhmamlbiijnphhppkpkmkl state=floating

# Default x settings
xset r rate 400 40

# Autostart applications
dropbox start &
pgrep compton || compton &
pgrep nitrogen || nitrogen --restore &
pgrep volumeicon || volumeicon &
pgrep light-locker || light-locker &
pgrep xfce4-power-manager || xfce4-power-manager &
pgrep nm-applet || nm-applet &

## Start panel
#pgrep xfce4-panel || xfce4-panel
pgrep tint2 || tint2 &
