#! /bin/sh

# Reload this file with Mod + Shift + R

# Keyboard event monitor
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color '#F3FF6F'
bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

# Application rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Orage state=floating
bspc rule -a Gpick state=floating
bspc rule -a R_x11 state=floating
bspc rule -a Thunar state=floating

# Tabs Outliner
bspc rule -a Chromium:crx_eggkanocgddhmamlbiijnphhppkpkmkl state=floating

# Default x settings
xset r rate 400 40

# Autostart applications
dropbox start &
pgrep nitrogen || nitrogen --restore &
pgrep volumeicon || volumeicon &
pgrep light-locker || light-locker &
pgrep xfce4-power-manager || xfce4-power-manager &
pgrep nm-applet || nm-applet &

# Start panel
pgrep tint2 || tint2 &
